### ISSUE TITLE
Crash if getWaveformDataWithCompletionBlock is called more than once

### ISSUE THREAD

**Issue by rahav** [syedhali/EZAudio#110]
I noticed that EZAudio will crash if ```getWaveformDataWithCompletionBlock``` is called more than once. In my case it was called with the same audio file (the one in provided in the example). It would fail in one of two ways:

1) Error: Failed to read audio data from audio file (-50), or
2) Crash in ```+(float)RMS:(float *)buffer``` method of EZAudio.m class.

In the second case debug shows that ```bufferSize``` has an unreasonably large value (e.g. 1065410462).

**Comment by goham** [comment]
I have the same problem and how to fix it?

**Comment by syedhali** [comment]
Should be fixed as of 0.3.0
