### ISSUE TITLE
how to change the EZAudioPlayer's volume

### ISSUE THREAD

**Issue by zjszyms** [syedhali/EZAudio#115]
how to change the EZAudioPlayer's volume

**Comment by sanderman123** [comment]
Probably not the best way, but it works. Look for this code snippet in EZOutput:

    // Get the available bytes in the circular buffer
    int32_t availableBytes;
    float *buffer = TPCircularBufferTail(circularBuffer,&availableBytes);
      
    // Ideally we'd have all the bytes to be copied, but compare it against the available bytes (get min)
    int32_t amount = MIN(bytesToCopy,availableBytes);
    memcpy( left,  buffer, amount );
    memcpy( right, buffer, amount );
    
Import the Accelerate framework into your project and into EZOutput. Then  change the code snippet into:
      
    // Get the available bytes in the circular buffer
    int32_t availableBytes;
    float *buffer = TPCircularBufferTail(circularBuffer,&availableBytes);
    
      //Added customisation for volume control:
      float volume = 0.5f;
      vDSP_vsmul(buffer, 1, &volume, buffer, 1, inNumberFrames);

      
    // Ideally we'd have all the bytes to be copied, but compare it against the available bytes (get min)
    int32_t amount = MIN(bytesToCopy,availableBytes);
    memcpy( left,  buffer, amount );
    memcpy( right, buffer, amount );
    
    
I guess you can make the volume variable in an instance variable for EZOutput and create your own get and set methods, so you can access the volume from your own app.
Hope it helps!

**Comment by maheshverma** [comment]
@sanderman123 Thanks a lot, it worked +1:

**Comment by maheshverma** [comment]
@sanderman123 Thank you, It works :)

**Comment by zjszyms** [comment]
谢谢！

**Comment by zjszyms** [comment]
@sanderman123 谢谢！

**Comment by joeldrotleff** [comment]
sanderman123's solution didn't work for me, but this did: http://stackoverflow.com/a/11577849/737387

Added a volume property to EZAudioFile, then added this code to the readFrames:audioBufferList:bufferSize:eof method:

```
float desiredGain = self.volume;
    for(UInt32 bufferIndex = 0; bufferIndex < audioBufferList->mNumberBuffers; ++bufferIndex) {
        float *rawBuffer = (float *)audioBufferList->mBuffers[bufferIndex].mData;
        vDSP_Length frameCount = audioBufferList->mBuffers[bufferIndex].mDataByteSize / sizeof(float);
        vDSP_vsmul(rawBuffer, 1, &desiredGain, rawBuffer, 1, frameCount);
    }
```

**Comment by syedhali** [comment]
As of 0.7.1 the EZAudioPlayer supports setting the volume (and pan!) by setting the volume property like so:
```objectivec
float volume =  // a value between 0 and 1
[self.player setVolume:volume];
```
