### ISSUE TITLE
Clear background color for EZAudioPlotGL

### ISSUE THREAD

**Issue by joeldrotleff** [syedhali/EZAudio#121]
This project is really awesome, great job.

Is there any way to make the background of the EZAudioPlotGL transparent? Setting backgroundColor to [UIColor clearColor] just makes it black it seems. I tried setting opaque to NO and that didn't help for the GL version of EZAudioPlotGL.

**Comment by Kowalik** [comment]
@joeldrotleff 
Did the solution really work for you? I can't make my EZAudioPlotGL transparent even if I set opaque of subviews YES (or No). Please give some advise.

**Comment by Kowalik** [comment]
@joeldrotleff 
I finally solved my problem. thanks anyway

**Comment by ZaidPathan** [comment]
@justin999 ,How did you find the solution, would you please explain here?
