### ISSUE TITLE
Failed to set client format on recorded audio file

### ISSUE THREAD

**Issue by andresteves** [syedhali/EZAudio#125]
Follow the  record example in Xcode 6.1 and using iOS 8 SDK but building for iOS 7+.
Error happens on both iPad Mini and iPhone 6. Even after request for using the micro it shows this error...

Error: Failed to set client format on recorded audio file (-66563).

**Comment by andresteves** [comment]
Careful if you include the example code in your own code and don't call the init for the controller you are showing.

**Comment by erikcore** [comment]
Hmm, I'm having a similar issue. Care to elaborate on how you resolved this?

**Comment by dddx80** [comment]
I'm also having the same issue. I moved parts of the code from sample project to my own project and every time I press record, program crashes with this error: Error: Failed to set client format on recorded audio file (-66563)
@andresteves and @erikcore  (how) did you solve this? Thanks

**Comment by griches** [comment]
If you have copied and pasted make sure you are initialised the microphone with: EZAudioPlotGLself.microphone = [EZMicrophone microphoneWithDelegate:self];

That's what fixed the crash for me.
