### ISSUE TITLE
Audio waveform amplitude, size, and shape issues

### ISSUE THREAD

**Issue by hfray** [syedhali/EZAudio#126]
![wavelength problems](https://cloud.githubusercontent.com/assets/10779908/5985066/437880a2-a8ab-11e4-8f7e-c1d55f027de8.png)

Audio waveform sizes are distorted. Some waveforms seem compressed, while others are stretched out. Additionally some waveforms have a think white line running straight through the middle.

**Comment by syedhali** [comment]
The weird split line thing has been fixed as of the 0.2.0 release. 

For the stretched out thing - the `getWaveformData` methods on the `EZAudioFile` provide a fixed amount of audio data for a plot. 

This works like so:
- A series of windows of samples are calculated, each the length of the total frames of the song divided by the number of points to calculate
- The root mean squared average of each window is used as the point value.

Hence, the shorter the song the more it will look stretched out. If you need a sample accurate waveform that stretches check out [FDWaveformView](https://github.com/fulldecent/FDWaveformView)
