### ISSUE TITLE
Bug in audioBufferListWithNumberOfFrames

### ISSUE THREAD

**Issue by SebastianMecklenburg** [syedhali/EZAudio#129]
There is a bug in the method audioBufferListWithNumberOfFrames of EZAudio. For non-interleaved audio with more than one channel the space for the additional AudioBuffers must be allocated. So it should be
```C++
   size_t memNeeded = sizeof(AudioBufferList);
   if(!interleaved) {
      memNeeded += (channels-1)*sizeof(AudioBuffer);
   }
   AudioBufferList *audioBufferList = (AudioBufferList*)malloc(memNeeded);
```

Otherwise you'll crash with a memory access error.

Regards,
Sebastian Mecklenburg

**Comment by syedhali** [comment]
This should be resolved in the 0.3.0 release
