### ISSUE TITLE
Override Input & Output

### ISSUE THREAD

**Issue by legendaryaman** [syedhali/EZAudio#130]
How to override input to built-in mic while using headphones through ez audio?

Thanks in advance.

**Comment by jorman86** [comment]
same problem here, if someone has any clue about this... it will be appreciated

**Comment by syedhali** [comment]
This is currently being worked on in the `play_file_cleanup` branch with the new EZAudioDevice for OSX and likely the AVAudioSession's input devices for iOS. It will look something like this: https://github.com/syedhali/EZAudio/blob/play_file_cleanup/EZAudio/EZMicrophone.m#L262

**Comment by syedhali** [comment]
You should be able to toggle whatever input device you need using the EZAudioDevice addition to the EZMicrophone
