### ISSUE TITLE
Getting the Buffer's byteArray

### ISSUE THREAD

**Issue by chokri** [syedhali/EZAudio#133]
Is That possible to get binary data from recorded buffer??

**Comment by syedhali** [comment]
For the EZMicrophone you can access the binary data via the EZMicrophoneDelegate method `microphone:hasBufferList:withBufferSize:withNumberOfChannels:`.

To get the binary data from the AudioBufferList you'd just do something like:
```objectivec
- (void)   microphone:(EZMicrophone *)microphone
        hasBufferList:(AudioBufferList *)bufferList
       withBufferSize:(UInt32)bufferSize
 withNumberOfChannels:(UInt32)numberOfChannels
{
    //
    // Binary data, if interleaved then bufferList->mNumberBuffers = 1 and
    // this is all the data
    //
    void *buffer = bufferList->mBuffers[0].mData;
    
    //
    // Binary data, if non-interleaved then each channel of data can be
    // found
    //
    for (int i = 0; i < bufferList->mNumberBuffers; i++)
    {
        void *channelBuffer = bufferList->mBuffers[i].mData;
    }
}
```

**Comment by GordonHuangYong** [comment]
@syedhali 
    for (int i = 0; i < bufferList->mNumberBuffers; i++)
    {
        void *channelBuffer = bufferList->mBuffers[i].mData;
       //save the pcm file. but playing noise.
        [self apppendAdpcmData:[NSData dataWithBytes:channelBuffer length:bufferList->mBuffers[i].mDataByteSize] toFile:@"luck.pcm"];
    }
