### ISSUE TITLE
Can I increase width of the wave?

### ISSUE THREAD

**Issue by kuntal33** [syedhali/EZAudio#138]
How can I increase the width of the wave? I have 15 seconds audio an I want my plot to fit through whole screen. Right now it stops on the half of the screen.

**Comment by syedhali** [comment]
Look into the `setRollingHistoryLength:` function on the EZAudioPlot and EZAudioPlotGL. Each time `updateBuffer:withBufferSize:` is called it appends one sample to the history buffer so this just depends on your sample rate. 

Assuming you're using the EZMicrophone's `microphone:hasAudioReceived:withBufferSize:withNumberOfChannels:`
44.1 kHz = 512 samples per callback = 86 times a second

<b>So for 15 seconds of audio you need a `rollingHistoryLength` of 86 * 15 = 1290</b>
