### ISSUE TITLE
Can I play audio file from server with this library?

### ISSUE THREAD

**Issue by kuntal33** [syedhali/EZAudio#139]
Can I play aduio file from server. 

Right now I tried to play audio from web server and app is crashing with below error.

Error: Failed to open audio file for reading ('wht?')

**Comment by syedhali** [comment]
EZAudio currently doesn't support streaming from a remote URL. I'd recommend the [DOUAudioStreamer](https://github.com/douban/DOUAudioStreamer) instead.
