### ISSUE TITLE
EZAudioPlayerDelegate reachedEndOfAudioFile not being called

### ISSUE THREAD

**Issue by jcavar** [syedhali/EZAudio#141]
Hello,
It seems that `reachedEndOfAudioFile` method is not being called at end of playback. I searched `EZAudioPlayer` class and i couldn't find any calls of that method at all. Am I doing something wrong maybe or this is bug?

**Comment by hakanw** [comment]
There's a pull request for it here https://github.com/syedhali/EZAudio/pull/104 but unfortunately the owner of this project hasn't merged it yet (like many other bug fixes available)

**Comment by jcavar** [comment]
Yeah, I understand. I will close this issue then. Thanks.
