### ISSUE TITLE
Changing the bufferSize in microphone

### ISSUE THREAD

**Issue by nevosegal** [syedhali/EZAudio#145]
Hi,

Is it possible to change the buffer size of the microphone function? i.e. the length of the buffer of data points and the number of times this function is getting called per second. It seems like the default size is 512 and I can't figure out how to change it.

**Comment by syedhali** [comment]
Please check out the answer for #185 for a code example of how to store more than 512 audio samples using an EZPlotHistoryInfo structure. 

Also, the [EZAudioFFTExample](https://github.com/syedhali/EZAudio/tree/master/EZAudioExamples/iOS/EZAudioFFTExample) has been updated to be a high resolution pitch detector using a 4096 length FFT.
![FFTExample](https://cloud.githubusercontent.com/assets/1275640/8662077/5621705a-2971-11e5-88ed-9a865e422ade.gif).
