### ISSUE TITLE
How to adjust the appearance of the histogram?

### ISSUE THREAD

**Issue by AzotKZN** [syedhali/EZAudio#146]
How do I want to look: 
![2015-04-11 19 12 59](https://cloud.githubusercontent.com/assets/5724450/7102103/ed98580e-e07e-11e4-9255-3f22d352d8aa.png)
As I look:
![2015-04-11 19 10 46](https://cloud.githubusercontent.com/assets/5724450/7102110/162f98b8-e07f-11e4-99f5-1de2c79182ee.png)
Where can I adjust all these parameters?

**Comment by syedhali** [comment]
Think you want to just adjust the gain property (try 3 or 4)
