### ISSUE TITLE
can i detect gender of speaker ?? (Like by getting pitch of voice).

### ISSUE THREAD

**Issue by cloudjanak** [syedhali/EZAudio#148]
The voiced speech of a typical adult male will have a fundamental frequency from 85 to 180 Hz, and that of a typical adult female from 165 to 255 Hz. Thus, the fundamental frequency of most speech falls below the bottom of the "voice frequency" band as defined above.

**Comment by syrakozz** [comment]
+1

**Comment by syedhali** [comment]
Hey guys, doing this kind of processing is out of the scope of EZAudio's core classes for now. In a future release I will be releasing a version of EZAudio that includes a graph-based way to chain audio nodes together that will make it much easier to just subclass a node to do this kind of analysis on whatever audio you have in your chain, but currently you'd have to do this kind of processing from the EZMicrophone delegate.
