### ISSUE TITLE
Branch new_examples Not Working in Xcode 6.3.1

### ISSUE THREAD

**Issue by andre991** [syedhali/EZAudio#154]
I cloned this project in repository, but when build, my xcode present this issues:
how do i solve this?
sorry for my english ;)
![captura de tela 2015-05-07 as 09 18 14](https://cloud.githubusercontent.com/assets/8302454/7515139/99060e8c-f49a-11e4-87ca-2b8b2a0970f1.png)

**Comment by syedhali** [comment]
Over the last week the new_examples branch has been broken up into smaller PRs and since has become deprecated. Please use the 0.4.0 release or current master branch.
