### ISSUE TITLE
Some functions and types are deprecated

### ISSUE THREAD

**Issue by lixing123** [syedhali/EZAudio#155]
For example, the AudioUnitSampleType and AudioSampleType, and AudioSessionSetProperty.
Is it necessary to remove/replace these deprecated functions/types?
I want to fork and fix these issues.

**Comment by syedhali** [comment]
As of 0.3.0 AudioUnitSampleType and AudioSampleType have just been replaced with floats and the AudioSession API has been replaced by using the AVAudioSession API instead so there aren't any of these warnings anymore!
