### ISSUE TITLE
Increase or decrease playback rate

### ISSUE THREAD

**Issue by andresteves** [syedhali/EZAudio#156]
Since my knowledge is limited, i would like to know how can one change the playback rate speed with EZAudioPlayer? Do i need to implement such method in the source code or there is a easier way to do it?

**Comment by andresteves** [comment]
Done it. Will submit soon.

**Comment by amitmalhotra** [comment]
@andresteves how did you calibrate the playback rate speed?

**Comment by andresteves** [comment]
Hi @amitmalhotra 

I end up using Superpowered framework and use the data from superpowered to feed the audioPlot.

Cheers

**Comment by ChiragCreative1** [comment]
@andresteves can you share some code, i dont know to use superpowered with audioPlot.
