### ISSUE TITLE
GL ERROR: 0x0502

### ISSUE THREAD

**Issue by serddmit** [syedhali/EZAudio#161]
Hello!
I have GL ERROR: 0x0502 and plots are drawing randomly - or on bottom part or top part, and sometimes (rarely) not drawing at all. Can someone help me please?

**Comment by syedhali** [comment]
Are you drawing multiple plots?

**Comment by syedhali** [comment]
Going to assume you're drawing multiple plots. If you still are having this issue use the `EZAudioPlot` instead. Since the 0.2.0 release the `EZAudioPlot` has had a dramatic increase in performance.

**Comment by vivekCZ** [comment]
I am drwaing multiple plot in once screen. I have same issue. When I popviewcontroller and again goes to same. It is not drawing any plot.But when I start recording its shows waves. I am getting GL ERROR: 0x0502

**Comment by yuedong56** [comment]
i have the same error
