### ISSUE TITLE
EZRecorder - Error: Failed to set client format on recorded audio file (-66563)

### ISSUE THREAD

**Issue by dddx80** [syedhali/EZAudio#163]
I'm using EZAudio in my project file and i'm trying to record an audio clip. I moved parts of the code from sample project EZAudioRecordExample to my own project and every time I press record, program crashes with this error: Error: Failed to set client format on recorded audio file (-66563). I've looked everywhere and I can't figure out the issue. Any help would be very much appreciated. Thanks

**Comment by syedhali** [comment]
Quickly looking at the error (-66563) looks like a `kExtAudioFileError_NonPCMClientFormat`. You can only set a linear PCM format as the EZAudioFile's client format. I think you may be trying to set the file format instead, however, the only supported file formats are m4a, wav, and aiff. 

See https://github.com/syedhali/EZAudio/blob/master/EZAudio/EZRecorder.h#L37-L51
```objectivec
/**
 To ensure valid recording formats are used when recording to a file the EZRecorderFileType describes the most common file types that a file can be encoded in. Each of these types can be used to output recordings as such:
 
 EZRecorderFileTypeAIFF - .aif, .aiff, .aifc, .aac
 EZRecorderFileTypeM4A  - .m4a, .mp4
 EZRecorderFileTypeWAV  - .wav
 
 */
typedef NS_ENUM(NSInteger, EZRecorderFileType)
{
    /**
     Recording format that describes AIFF file types. These are uncompressed, LPCM files that are completely lossless, but are large in file size.
     */
    EZRecorderFileTypeAIFF,
    /**
     Recording format that describes M4A file types. These are compressed, but yield great results especially when file size is an issue.
     */
    EZRecorderFileTypeM4A,
    /**
     Recording format that describes WAV file types. These are uncompressed, LPCM files that are completely lossless, but are large in file size.
     */
    EZRecorderFileTypeWAV
};
```

**Comment by dddx80** [comment]
thanks for your response syedhali. This is the line of code where I initialize the recorder:

self.recorder = [EZRecorder recorderWithDestinationURL:[NSURL fileURLWithPath:kAudioFilePath] sourceFormat:self.microphone.audioStreamBasicDescription destinationFileType:EZRecorderFileTypeM4A];

This is the line giving me the error but when i comment this line out, i don't get that error anymore. However, the recorder does not record if i don't initialize it. 

I used your example files from EZAudioRecordExample project. I made sure everything from RecordViewController.m and RecordViewController.h was properly moved. I also added the proper switches, buttons ad labels. But still same error. 

Is there any other way to initialize the recorder?

**Comment by gotuckgo** [comment]
I had the same weirdness and error.  For me it came down to declaring microphone a strong instead of a weak reference.  When I looked at microphone in the debugger after it was instantiated it looked fine, but microphone was getting freed up by the OS at some point before the recorder init call and providing bad values (all zeros.)

**Comment by syedhali** [comment]
@dddx80 Like @gotuckgo said, make sure you've first created your EZMicrophone instance or else `self.microphone.audioStreamBasicDescription ` will be invalid. Please update to EZAudio 0.7.2 and let me know if this is still an issue (going to close this for now)
