### ISSUE TITLE
new here, need help with bpm/tempo

### ISSUE THREAD

**Issue by brunork26** [syedhali/EZAudio#168]
Hey, 

I'm new to iOS and audio programming,

I'm looking for a way to get the audio waveform informations, to create a 2D platform game.

Me and my friends were using the EZAudioWaveformFromFileExemple as base, but we got stuck on the method "openFileWithFilePathURL", we can get the waveformData and print it, we may be able to get waves high and length but it doesn't look like the whole file... well I may be wrong...

Any ideas? Any help is appreciated!

Thanks

**Comment by syedhali** [comment]
This is a duplicate on #38. EZAudio doesn't provide any mechanism to actually perform BPM or Pitch detection, but you could consider one of the following libraries:
1.) [aubio](http://aubio.org/) - probably one of the best, free for non-commercial
2.) [SoundTouch](http://www.surina.net/soundtouch/) - free for non-commercial
3.) [BeatDetektor](https://github.com/cjcliffe/beatdetektor) - haven't used, but is MIT so free for commercial + non-commercial use

**Comment by hsin919** [comment]
Hi I found another good framework for bit detection named superpowered sdk. Here is the [sample](https://github.com/hsin919/Low-Latency-Android-Audio-iOS-Audio-Engine/tree/master/SuperpoweredOfflineAnalyzerExample) code for `SuperpoweredOfflineAnalyzer` FYI
