### ISSUE TITLE
Error: Failed to fill complex buffer in float converter ('insz')

### ISSUE THREAD

**Issue by jamrader** [syedhali/EZAudio#173]
When I open the FFT example project and run it on my iPhone, the project immediately shuts down and I'm given the error: "Error: Failed to fill complex buffer in float converter ('insz')". The project will, however, work in the simulator. Anyone have any experience solving this?

**Comment by syedhali** [comment]
What iOS device are you running it on?

**Comment by jamrader** [comment]
iPhone 6

**Comment by jamrader** [comment]
It seems the error is completely random. Either it works and will continue to work (for a few runs), then the errors comes and every time I run it, it comes. I'm not changing anything in the project.

**Comment by jamrader** [comment]
It is seriously the weirdest error. What is setting off the error is this:

1) I ran the FFT audio project and got the error Failed to fill complex buffer in float converter ('insz').

2) I ran the EZAudioRecordings project: no error.

3) Run the FFT audio project: no error.

Then I answered I phone call. I ran the FFT audio project again and got the error. I repeated steps 2 and 3: no error.

**Comment by syedhali** [comment]
Ahhhh I see, the reason it is crashing seems to be because sometimes it is unable to capture the audio coming in the microphone. Specifically, I forgot to set the audio session on that project...heh.

Try adding this to the top of the iOS FFT example in `viewDidLoad` before creating the `EZMicrophone`:
```objectivec
//
// Setup the AVAudioSession. EZMicrophone will not work properly on iOS
// if you don't do this!
//
AVAudioSession *session = [AVAudioSession sharedInstance];
NSError *error;
[session setCategory:AVAudioSessionCategoryPlayAndRecord error:&error];
if (error)
{
    NSLog(@"Error setting up audio session category: %@", error.localizedDescription);
}
[session setActive:YES error:&error];
if (error)
{
    NSLog(@"Error setting up audio session active: %@", error.localizedDescription);
}
```

**Comment by jamrader** [comment]
Great. It seems to be working. Thank you for your awesome code.
