### ISSUE TITLE
AUGraph cleanup on EZOutput dealloc causes crash

### ISSUE THREAD

**Issue by gotuckgo** [syedhali/EZAudio#176]
The augraph clean up on EZOutput dealloc is: stop, close, uninitialize.  The uninitialize call fails on iPad with OX8 with error -2147450879.  Should the order be: stop, uninit, close?  I tried this and it fixed the error for me, but I couldn't find anything definitive on the right sequence for teardown.

**Comment by syedhali** [comment]
Ah that makes sense. Could you submit a PR? If not, just let me know and I'll make the tweak in the next release.

**Comment by syedhali** [comment]
This has been resolved as of the 0.7.2 release. Needed to call `DisposeAUGraph`
