### ISSUE TITLE
'AudioSessionGetProperty' is deprecated: first deprecated in iOS 7.0

### ISSUE THREAD

**Issue by think-dev** [syedhali/EZAudio#18]
Seems that AudioSessionGetProperty is deprecated for iOS 7.0 for some files. Here are the exact places:

/EZAudio/EZOutput.m:270:24: 'AudioSessionGetProperty' is deprecated: first deprecated in iOS 7.0

/EZAudio/EZMicrophone.m:450:26: 'AudioSessionGetProperty' is deprecated: first deprecated in iOS 7.0

/EZAudio/EZMicrophone.m:468:28: 'AudioSessionSetProperty' is deprecated: first deprecated in iOS 7.0

/EZAudio/EZMicrophone.m:474:28: 'AudioSessionGetProperty' is deprecated: first deprecated in iOS 7.0

**Comment by syedhali** [comment]
The AudioSession API was removed in 0.0.6 and has since been replaced with the AVAudioSession API.

**Comment by warpling** [comment]
Awesome!
