### ISSUE TITLE
Increase Hz precision / buffer size

### ISSUE THREAD

**Issue by jamrader** [syedhali/EZAudio#185]
I'm trying to increase the accuracy of my FFTViewController so that when I play a sound of a specific Hz, it can guess it with better accuracy than what it has by default. I believe this is linked to its buffer size (512 currently). Is there any way I can do this? Are there any drawbacks? I've seen this issue (https://github.com/syedhali/EZAudio/issues/84) but was ultimately left without a solution.

**Comment by syedhali** [comment]
Hey @jamrader, just added the [EZAudioFFTRolling](https://github.com/syedhali/EZAudio/blob/master/EZAudio/EZAudioFFT.h#L247) in the 1.1.0 release. In the implementation you'll see how to use a EZPlotHistoryInfo structure to collect a larger number of samples to use for getting a much higher resolution FFT. 

Specifically,
```objectivec
// Use the EZPlotHistoryInfo structure to hold the audio history data while also having access to a current window of audio data
@property (assign, nonatomic) EZPlotHistoryInfo *historyInfo;

// Allocate an appropriately sized history buffer in bytes
self.historyInfo = [EZAudioUtilities historyInfoWithDefaultLength:(UInt32)windowSize
                                                    maximumLength:(UInt32)historyBufferSize];

// Append buffer to history window
[EZAudioUtilities appendBuffer:buffer
                withBufferSize:bufferSize
                 toHistoryInfo:self.historyInfo];
```

Specifically, for what you're trying to do check out the new [EZAudioFFTExample](https://github.com/syedhali/EZAudio/tree/master/EZAudioExamples/iOS/EZAudioFFTExample), which is now just a pitch detector that uses the EZAudioFFTRolling to get the frequency with the highest energy and converts it to a musical note:
![FFTExample](https://cloud.githubusercontent.com/assets/1275640/8662077/5621705a-2971-11e5-88ed-9a865e422ade.gif)

**Comment by jamrader** [comment]
Are you no longer required to add 

    AVAudioSession *session = [AVAudioSession sharedInstance];
    NSError *error;
    [session setCategory:AVAudioSessionCategoryPlayAndRecord error:&error];
    if (error)
    {
        NSLog(@"Error setting up audio session category: %@", error.localizedDescription);
    }
    [session setActive:YES error:&error];
    if (error)
    {
        NSLog(@"Error setting up audio session active: %@", error.localizedDescription);
    }


to     viewDidLoad before the microphone is created?

**Comment by syedhali** [comment]
Whoops, yeah you need the AVAudioSession stuff. Just updated 1.1.2 to have that fix.

**Comment by orkenstein** [comment]
@syedhali, I'm not sure why, but I'm getting incorrect frequency for generated tone. This is true for your  EZAudioFFTExample project. For example, you generate sound at 440hz, but it shows 441.43.
Values are incorrect all the way.
The other problem is that `fft.maxFrequencyMagnitude` changes quite randomly. I generate constant sound, but it changes all the time. 
Any thoughts?

**Comment by jrader22** [comment]
You're accuracy is dependent on your sample rate (say 44100) and your number of bins (say 512). That means each bin is about 86 Hz, so you're accuracy would only be exactly that, 86 Hz. Having enough accuracy to only be off by 1.4 Hz is pretty accurate actually.

**Comment by orkenstein** [comment]
@jrader22, thanks for your reply!
Not sure, what "bin" is. Could you please explain.
After all, how to increase accuracy?
