### ISSUE TITLE
ios6.1 when record got "Error: Failed to write audio data to recorded audio file (-66570)"

### ISSUE THREAD

**Issue by robotsu** [syedhali/EZAudio#195]
This is happened when record use EZRecorder to record.

Device console shows many of "<Error>: objc[600]: Object 0x1e.... of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug"

PS. No error in iOS7.0.

Any clues? 

Thanks.

**Comment by syedhali** [comment]
Hm, are you sure you're using EZAudio 1.0.0 or greater? 66570 corresponds to an async write error (kExtAudioFileError_AsyncWriteBufferOverflow), which can't really happen because the write has been moved to be synchronous since 1.0.0.

**Comment by robotsu** [comment]
@syedhali  Thank you for your very quick reply. Sorry I am using 0.5, so if I use 1.0.0+, my problem will not happen right?
Thanks.

**Comment by robotsu** [comment]
Sorry I am using 0.0.5, shows in VERSION file.

**Comment by syedhali** [comment]
Well, try it :) If you're still having this issue just let me know.
