### ISSUE TITLE
Error: Failed to fill complex buffer in float converter ('insz')

### ISSUE THREAD

**Issue by edwardvalentini** [syedhali/EZAudio#203]
Im trying to add an audioplot to my app and I get the error:

`Error: Failed to fill complex buffer in float converter ('insz')`

when I try to use this callback.   Even if the definition is empty I get this error.   I need to remove the callback entirely in order not to get the error.

```
-(void)microphone:(EZMicrophone *)microphone
      hasAudioReceived:(float **)buffer
        withBufferSize:(UInt32)bufferSize
  withNumberOfChannels:(UInt32)numberOfChannels {
    
...

}
```

Has anyone had this issue?

**Comment by griches** [comment]
I have this issue sporadically. Cannot find the cause annoyingly and happens rarely enough that I can't debug it.

**Comment by griches** [comment]
This fixed it for me: https://github.com/syedhali/EZAudio/issues/173

**Comment by syedhali** [comment]
Nice!

**Comment by hyd00** [comment]
Please someone check this issue https://github.com/syedhali/EZAudio/issues/246

same problem occurring now in iPhone 6s and 6S Plus

**Comment by davidwadge** [comment]
Also having the same issue on 6S and the solution above doesn't work.

**Comment by cmmartin** [comment]
Make sure you set the category and activate your AVAudioSession instance *before* you instantiate the EZMicrophone or any other EZAudio specific code. Even if they are in the same method. I ran into this issue on the 6s and was able to resolve it that way
