### ISSUE TITLE
BAD ACCESS when switching to background and using EZAudioPlotGL

### ISSUE THREAD

**Issue by augmentedworks** [syedhali/EZAudio#21]
This appears in the EZAudioOpenGLWaveformExample too.

I noticed that it appears:

- When using EZAudioPlotGL (the core graphics alternative doesn't crash).
- Immediately after entering background state.
- Only on real device (at least on my iPhone 5, iOS 7.04).

Activating the zombies doesn't give any further info...

**Comment by nmcc24** [comment]
It may not be the most perfect solution but does the job in this situation: keeps the buffer updated but does not draw while the app is in background.

In EZAudioPlotGLKViewController's glkView:drawInRect: insert this before the existing code:

//EZAudioPlotGL is currently crashing while drawing in background. Thus, we only allow the plot to be drawn if the app is in foreground
    if ([UIApplication sharedApplication].applicationState != UIApplicationStateActive) {
        return;
    }

**Comment by syedhali** [comment]
This has been fixed as of the 0.7.1 release
