### ISSUE TITLE
Cocoapods version 1.1.2 does not exist

### ISSUE THREAD

**Issue by rednebmas** [syedhali/EZAudio#224]
In the README it says to install version 1.1.2 but I get the following error after the `pod install command`

```
[!] Unable to satisfy the following requirements:

- `EZAudio (~> 1.1.2)` required by `Podfile`
```
After changing the version to 1.1.1 it works correctly.

**Comment by syedhali** [comment]
Whoops, sorry about that - just pushed 1.1.2 to the pods repo. Should be there in ~15 minutes

**Comment by syedhali** [comment]
Done!
