### ISSUE TITLE
how to get mono input real time passthrough to play on both output channels?

### ISSUE THREAD

**Issue by player500** [syedhali/EZAudio#228]
Hi, can someone help me with this problem? For passthrough implementation, with the default output overridden via `microphone.output = speaker` and with a mono source attached to the `EZMicrophone`, I can only hear audio in the left channel, and not both channels. 
A recorded mono segment plays properly on both channels via `EZAudioOutput`. Anyone have an idea how to get passthrough to work with both channels? Thanks!

**Comment by player500** [comment]
Found the answer: have to replace `microphone.output = speaker'
with `speaker.dataSource = microphone`

**Comment by wstcyx** [comment]
how to fix it ? i don't understand

**Comment by kosso** [comment]
Did you figure out how to get the PassThrough demo to reach both left and right earphones?
