### ISSUE TITLE
EZAudioPlot show plot on Simulator but nothing on my real device

### ISSUE THREAD

**Issue by Tommecpe** [syedhali/EZAudio#25]
Thank you for this wonderful Library.

I'm trying to show a `EZAudioPlot` responding to my Microphone output.
It is working great on my Simulator. but nothing show on my iPhone.

I accept the use of the microphone, I don't know why I've got nothing.

I'm I missing something obvious ?

**Comment by syedhali** [comment]
Hi, not sure if this is still an issue, but check out the [EZAudioCoreGraphicsWaveformExample](https://github.com/syedhali/EZAudio/tree/master/EZAudioExamples/iOS/EZAudioCoreGraphicsWaveformExample) to see how to incorporate the plot into your code. Specifically your viewDidLoad should look something like:
```objectivec
- (void)viewDidLoad
{
    [super viewDidLoad];
    
    //
    // Setup the AVAudioSession. EZMicrophone will not work properly on iOS
    // if you don't do this!
    //
    AVAudioSession *session = [AVAudioSession sharedInstance];
    NSError *error;
    [session setCategory:AVAudioSessionCategoryPlayAndRecord error:&error];
    if (error)
    {
        NSLog(@"Error setting up audio session category: %@", error.localizedDescription);
    }
    [session setActive:YES error:&error];
    if (error)
    {
        NSLog(@"Error setting up audio session active: %@", error.localizedDescription);
    }

    // Plot type
    self.audioPlot.plotType = EZPlotTypeBuffer;

    //
    // Create the microphone
    //
    self.microphone = [EZMicrophone microphoneWithDelegate:self];
}
```

Feel free to reopen this ticket if it is still an issue
