### ISSUE TITLE
Custom ABSD ignored when using EZMicrophone init methods

### ISSUE THREAD

**Issue by chrisballinger** [syedhali/EZAudio#27]
`initWithMicrophoneDelegate:withAudioStreamBasicDescription:` and its "instant" counterpart ignore the ABSD passed into the method because `_createInputUnit` is called in the call to `initWithMicrophoneDelegate:`.

When trying to work around the issue doesn't seem to work either because no audio frames are delivered.

```obj-c
int preferredSampleRate = 48000;
AVAudioSession *audioSession = [AVAudioSession sharedInstance];
[audioSession setPreferredSampleRate:preferredSampleRate error:&error];
AudioStreamBasicDescription absd = [EZAudio monoCanonicalFormatWithSampleRate: preferredSampleRate];
self.microphone = [[EZMicrophone alloc] initWithMicrophoneDelegate:self];
[self.microphone setAudioStreamBasicDescription:absd];
[self.microphone startFetchingAudio];
```

**Comment by orkenstein** [comment]
Hi everybody! 
So any solution is available now? I need custom sample rate. Cause EZAudioPlot freezes the whole app when using EZMicrophone.

**Comment by Ronileco** [comment]
I believe I have the same issue.
I can't set the mic sample rate, it overrides my configuration no matter how I try it.

Should I just move to the core audio session? or is there something I'm missing.
Thanks.

**Comment by ogoldfinger** [comment]
The problem is the everything gets initialized BEFORE the custom absd is applied. What worked for me is just reinitializing. You can refactor this a bit more but what worked for me is calling `_createInputUnit` again after my absd is set:

    -(EZMicrophone *)initWithMicrophoneDelegate:(id<EZMicrophoneDelegate>)microphoneDelegate
            withAudioStreamBasicDescription:(AudioStreamBasicDescription)audioStreamBasicDescription {
      self = [self initWithMicrophoneDelegate:microphoneDelegate];
      if(self){
        _customASBD  = YES;
        streamFormat = audioStreamBasicDescription;
        [self _createInputUnit]; // ADD THIS LINE TO RE-INITIALIZE
      }
      return self;
}

**Comment by chenjishi** [comment]
@ogoldfinger your method worked for me also!

**Comment by syedhali** [comment]
As of 0.1.0 release the EZMicrophone was rewritten to better support custom AudioStreamBasicDescription so you should just be able to use the initializer:

```objectivec
/**
 Creates an instance of the EZMicrophone with a delegate to respond to the audioReceived callback. This will not start fetching the audio until startFetchingAudio has been called. Use microphoneWithDelegate:startsImmediately: to instantiate this class and immediately start fetching audio data.
 @param 	delegate 	A EZMicrophoneDelegate delegate that will receive the audioReceived callback.
 @param 	audioStreamBasicDescription A custom AudioStreamBasicFormat for the microphone input.
 @return	An instance of the EZMicrophone class. This should be declared as a strong property!
 */
+ (EZMicrophone *)microphoneWithDelegate:(id<EZMicrophoneDelegate>)delegate
         withAudioStreamBasicDescription:(AudioStreamBasicDescription)audioStreamBasicDescription;
```
