### ISSUE TITLE
MPMediaItem URL error

### ISSUE THREAD

**Issue by rikola** [syedhali/EZAudio#279]
I can't create an `EZAudioFile` from an `MPMediaItem` URL in my app. When I try to do it I get this error `Error: Failed to dispose of ext audio file (-50)`.  
Do you know how to get it to work with iTunes library URL's?

**Comment by dennislysenko** [comment]
One possible workaround would be to quickly copy the iTunes library URL to a file that you know EZAudioFile can work with. Here is a gist that provides a class with a single method to do just that:

https://gist.github.com/abeldomingues/fe8fa797fd55603f2f4a

**Comment by rikola** [comment]
Thanks. This looks like it will do the trick.  
I'm still not sure why the ipod URL prefix breaks EZAudioFile though. Strange stuff.

**Comment by bintu1234** [comment]
@rikola  I am also facing same issue in objective c, How you resolve thjis issue Please help me

**Comment by vickydhas** [comment]
Hey friends, Anybody got hold of this issue. Still get this error

**Error: Failed to dispose of ext audio file (-50) error**, and suspect this happens if the playing file is recorded with very small interval of 3-4 sec.

**Comment by appdisc** [comment]
> Error: Failed to dispose of ext audio file (-50) error

The same error.Error: Failed to dispose of ext audio file (-50) error
