### ISSUE TITLE
CocoaPods add EZAudio in swift problem

### ISSUE THREAD

**Issue by Seppuu** [syedhali/EZAudio#284]
My project is swift based.ago,I use CocoaPods and swift objective-c bridge file to using EZAudio successfully. That's cool. EZAudio helped me quite a lot .Thanks.
Today,when I want to add a swift written library via cocoapods using #Uncomment this line if you're using Swift
#use_frameworks! 

as needed,  swift objective-c bridge file should never be used if I add  "use_frameworks! "in podfile.
then,"import  EZAudio" at  swift.file .Xcode complains that "Could not build Objective-C module 'EZAudio'".

am I describe things clearly?

**Comment by ceeyang** [comment]
@jidanyu   how did you solve it ?

**Comment by jidanyu** [comment]
@ceeyang 这个问题时间有点长了，我不记得了。
