### ISSUE TITLE
Help with implementing EZAudioPlayerDelegate in Swift

### ISSUE THREAD

**Issue by parsley75** [syedhali/EZAudio#294]
Hi,
I'm struggling converting this code in your EZAudioPLayer example
```
// Declare the EZAudioFile as a strong property
@property (nonatomic, strong) EZAudioFile *audioFile;

...

// Create an EZAudioPlayer with a delegate that conforms to EZAudioPlayerDelegate
self.player = [EZAudioPlayer audioPlayerWithDelegate:self];
```

to swift. Can anyone help please? Especially if i need more code to ensure it works
I realise this may be basic for most of you, So thanks in advance

Kind Regards

Mark

**Comment by freak4pc** [comment]
It should just be 

```swift
var audioFIle: EZAudioFile!

self.audioFile = EZAudioPlayer(delegate: self)
```

**Comment by parsley75** [comment]
thanks @freak4pc , i really could come round and hug you. 
i'd solved many of the delegate problems and that was the final piece of the puzzle.
i suppose its the trouble with learning ios apps and swift and audio at the same time. thanks again

**Comment by freak4pc** [comment]
Sure thing. Good luck!
