### ISSUE TITLE
OutputRenderCallback doesn't support interleaved samples

### ISSUE THREAD

**Issue by ammmir** [syedhali/EZAudio#30]
When using circular buffers, appendDataToCircularBuffer:fromAudioBufferList: correctly appends data from the first buffer in the AudioBufferList, but EZOutput's OutputRenderCallback assumes there are two buffers, one for each channel. This causes a crash, as the right channel buffer points to an invalid memory location or NULL. Shouldn't this be configurable so if my data is already interleaved, it should look at the ASBD and deinterleave appropriately?

**Comment by syedhali** [comment]
As of 0.7.1 you can provide an interleaved format as the `inputFormat` to the EZOutput during initialization like so:
```objectivec
AudioStreamBasicDescription inputFormat = [EZAudioUtilities stereoFloatInterleavedFormatWithSampleRate:44100.0f];
self.output = [EZOutput outputWithDataSource:self inputFormat:inputFormat];
```
