### ISSUE TITLE
"Error: Failed to create new audio converter (-50)"

### ISSUE THREAD

**Issue by alecgorge** [syedhali/EZAudio#31]
No matter what I pass into `[EZRecorder recorderWithDestinationURL:andSourceFormat:]`, it always prints this error message:

    Error: Failed to create new audio converter (-50)

Are there limitations on the `AudioStreamBasicDescription` that can be used? Do the descriptions for `EZMicrophone` and `EZRecorder ` have to match?

I'm trying to output to `aac` but this `AudioStreamBasicDescription` doesn't work:

    struct AudioStreamBasicDescription desc;
    
    desc.mSampleRate = 44100;
    desc.mFormatID = kAudioFormatMPEG4AAC;
    desc.mFormatFlags = 0;
    desc.mBytesPerPacket = 2; // must have a value or won't write apparently
    desc.mFramesPerPacket = 0;
    desc.mBytesPerFrame = 0;
    desc.mChannelsPerFrame = 1;
    desc.mBitsPerChannel = 0;
    desc.mReserved = 0;

**Comment by syedhali** [comment]
The EZRecorder and EZMicrophone must have the same format, see the 
[EZAudioRecordingExample](https://github.com/syedhali/EZAudio/tree/master/EZAudioExamples/iOS/EZAudioRecordExample). The format you are setting on the EZRecorder is the client format, not the file format.
 
Think of the client format as the common language that allows the component to talk to other components in the context of an application, independent of what the actual file format is on disk. The client format must be linear PCM to work properly (the mic is always linear PCM). 

Meanwhile, the file format is determined when you initialize the EZRecorder using one of the destination file types enumerated below:

```objectivec
/**
 To ensure valid recording formats are used when recording to a file the EZRecorderFileType describes the most common file types that a file can be encoded in. Each of these types can be used to output recordings as such:
 
 EZRecorderFileTypeAIFF - .aif, .aiff, .aifc, .aac
 EZRecorderFileTypeM4A  - .m4a, .mp4
 EZRecorderFileTypeWAV  - .wav
 
 */
typedef NS_ENUM(NSInteger, EZRecorderFileType)
{
    /**
     Recording format that describes AIFF file types. These are uncompressed, LPCM files that are completely lossless, but are large in file size.
     */
    EZRecorderFileTypeAIFF,
    /**
     Recording format that describes M4A file types. These are compressed, but yield great results especially when file size is an issue.
     */
    EZRecorderFileTypeM4A,
    /**
     Recording format that describes WAV file types. These are uncompressed, LPCM files that are completely lossless, but are large in file size.
     */
    EZRecorderFileTypeWAV
};
```

Usage:
```objectivec
self.recorder = [EZRecorder recorderWithDestinationURL:[self testFilePathURL]
                                          sourceFormat:self.microphone.audioStreamBasicDescription
                                   destinationFileType:EZRecorderFileTypeM4A];
```

**Comment by KevinGong2013** [comment]
If i want take a .wav file, just change EZRecorderFileTypeM4A to EZRecorderFileTypeWAV ?
Actually i did it then app crashed.
error message : Error: Failed to create audio file ('fmt?')

if i set destinationFileType to EZRecorderFileTypeM4A it's works fine.

**Comment by Michael00767** [comment]
I got same problem as same as @KevinGong2013 .Did you finger it out?

**Comment by Michael00767** [comment]
All right, I found some way to fixed that problem according to http://stackoverflow.com/questions/13171563/ios-extaudiofilecreatewithurl-getting-error-creating-file-fmt
I change file in EZAudio/Core/EZRecorder.m line 263
audioFileTypeID = kAudioFileWAVEType;
to
audioFileTypeID = kAudioFileCAFType;
it work!But I think the formate maybe change to caf from wav.
@KevinGong2013

**Comment by KevinGong2013** [comment]
Thanks. I've used another plugin. Next time I'll follow this. :)

**Comment by SeoBright** [comment]
Hello. I can not record audio as WAV with EZRecorder.
I can try as following.

self.audioRecorder = [EZRecorder recorderWithURL:[self testFilePathURL]
                                            clientFormat:self.microphone.audioStreamBasicDescription
                                                fileType:EZRecorderFileTypeWAV];

Hope to reply soon. Thanks for your time.

**Comment by DaesikJang** [comment]
Hello. I got the same problem and solved by changing the formatForFileType for EZRecorderFileTypeWAV format as follows.(in EZRecorder.m file)
+ (AudioStreamBasicDescription)formatForFileType:(EZRecorderFileType)fileType
                                withSourceFormat:(AudioStreamBasicDescription)sourceFormat
{
    AudioStreamBasicDescription asbd;
    switch (fileType)
    {
        case EZRecorderFileTypeWAV:
            asbd =  [EZAudioUtilities monoFloatFormatWithSampleRate:sourceFormat.mSampleRate];
            //asbd = [EZAudioUtilities stereoFloatInterleavedFormatWithSampleRate:sourceFormat.mSampleRate];

**Comment by ZhouXingXingOrJames** [comment]
YES，I Agreed jang
