### ISSUE TITLE
Trying to Use EZAudioPlayer, but crashes

### ISSUE THREAD

**Issue by bennettl** [syedhali/EZAudio#316]
For iOS, I saved a .m4a file to the documents directory with EZMicrophone and EZRecorder. When I used EZAudioPlayer to play the file, I received:

Error: Failed to create ExtAudioFileRef ('dta?')

And the app crashes.

**Comment by syedhali** [comment]
For the EZRecorder make sure you call the `close` function because trying to read it back.

**Comment by bennettl** [comment]
@syedhali Thanks for the reply. I tried not even instantiating the EZMicrophone or EZRecorder, just using the EZAudioPlayer to play the EZAudioFile. Received the same error.

**Comment by bennettl** [comment]
THANK YOU @syedhali
