### ISSUE TITLE
Routing sound that's been filtered

### ISSUE THREAD

**Issue by foozmeat** [syedhali/EZAudio#32]
Hi, thanks again for the great library!

I'm filtering incoming audio (from the mic) in 
```
-(void)microphone:(EZMicrophone *)microphone
 hasAudioReceived:(float **)buffer
   withBufferSize:(UInt32)bufferSize
withNumberOfChannels:(UInt32)numberOfChannels
```

and it's working fine. I'd like to hear in the headphones what it sounds like after filtering but I'm just getting the unfiltered audio. It seems like I should be putting my filtered buffer data in the the circular buffer but it's not clear to me how that should work. Can you advise?

Thank you

**Comment by syedhali** [comment]
As of version 0.3.0 there's been a few changes that will make this much easier. 
1.) The EZMicrophone supports direct out so you can hear the microphone input by using the `setOutput:` method.
2.) You can process the microphone's incoming audio via the EZMicrophoneDelegate method, `microphone:hasBufferList:withBufferSize:withNumberOfChannels:`

For example, 
```objectivec
- (void)viewDidLoad
{
    // 
    // Create an EZMicrophone instance
    //
    self.microphone = [EZMicrophone microphoneWithDelegate:self];

    //
    // Set the EZOutput singleton as the EZMicrophone's output
    //
    [self.microphone setOutput:[EZOutput sharedOutput]];

    // 
    // Start the microphone
    //
    [self.microphone startFetchingAudio];

    //
    // Start the output
    //
    [[EZOutput sharedOutput] startPlayback];
}

- (void)   microphone:(EZMicrophone *)microphone
        hasBufferList:(AudioBufferList *)bufferList
       withBufferSize:(UInt32)bufferSize
 withNumberOfChannels:(UInt32)numberOfChannels
{
    //
    // Process audio (here we're just silencing it)
    //
    for (int i = 0; i < bufferList->mNumberBuffers; i++)
    {
        memset(bufferList->mBuffers[i].mData,
               0,
               bufferList->mBuffers[i].mDataByteSize);
    }
}
```
