### ISSUE TITLE
EZAudioPlot background color to transparent.

### ISSUE THREAD

**Issue by elprl** [syedhali/EZAudio#45]
Hi,

Is it possible to set the EZAudioPlot view to be transparent?
// doesn't seem to work
self.audioPlot.backgroundColor = [UIColor clearColor];

The background goes black.

**Comment by Kowalik** [comment]
Hi @syedhali 
In order to get clear background, I tried "opaque value to NO" and modified EZAudioPlotGLKViewController.m so that background color become clear color. However, I was not able to get clear background of EZAudioPlotGL. 
Any suggestion will be helpful. thanks,
