### ISSUE TITLE
Clear background color

### ISSUE THREAD

**Issue by tspecht** [syedhali/EZAudio#46]
First off all: Great project!
I integrated your code and am using a EZAudioPlot to display the waveform auf the audio. I would really like to have the plot use a clear background but unfortunately settings the background color attribute to [UIColor clearColor] doesn't solve the issue. Any ideas?

**Comment by swaroopbutala** [comment]
For some reason I was not able to get clear background just by setting background color and opaque on audioPlot. I also did set the backgroundColor to clearColor and opaque to false on all of its subviews. Else I was seeing black background. E.g code:

        for subview in self.audioPlot.subviews {
            var subview1 = subview as UIView
            subview1.opaque = false
            subview1.backgroundColor = UIColor.clearColor()
        }

**Comment by Kowalik** [comment]
Hi @syedhali 
In order to get clear background, I tried "opaque value to NO" and modified EZAudioPlotGLKViewController.m so that background color become clear color. However, I was not able to get clear background of EZAudioPlotGL. 
Any suggestion will be helpful. thanks,

**Comment by Kowalik** [comment]
@syedhali 
I finally solved my problem. thanks anyway

**Comment by solomon23** [comment]
@Kowalik how was this solved ? I'm running into the same issue
