### ISSUE TITLE
How to change the buffer size to increase FFT window? 

### ISSUE THREAD

**Issue by JeanRintoul** [syedhali/EZAudio#50]
Whenever I try to hardcode buffersize into [self.audioPlot updateBuffer:buffer[0] withBufferSize:bufferSize]; I get a crash so I am wondering how to set up the audio stream to window at 8820 instead of 512 samples. The microphone and hardware will be the same, but I need the higher buffersize to get more resolution when doing an FFT. I feel like there is some simple part of setting up the microphone or bufffer that I have not understood. Please halp!  
Thanks.

**Comment by gopdahl** [comment]
Where and how do you initialize the _fftBuf, _fftBufIndex, and _samplesRemaining? 
If I do it in the microphoneDelegate they get initialized every time it's called and the next 512 samples from the buffer never get appended to the _fftBuf.
