### ISSUE TITLE
EZAudioPlot Buffer drawing issue

### ISSUE THREAD

**Issue by kwade101** [syedhali/EZAudio#55]
Hello.  Absolutely fantastic library!  I'm enjoying using it.  However, I do have a question about the results of the EZAudioPlot buffer drawing.  When I run the EZAudioWaveformFromFileExample project, the resulting waveform has an ever increasing gap of background color on the center line.  There is no gap on the left.  But on the right side it becomes noticeable (screen shot below).  Any ideas what is causing this?  I assume there might be something amiss in drawRect?

![ios simulator screen shot may 21 2014 5 21 18 pm](https://cloud.githubusercontent.com/assets/7563587/3046908/d274c7b0-e12e-11e3-88b9-4ec3cbedf74b.png)

**Comment by syedhali** [comment]
This should be fixed as of the 0.7.1 release!
