### ISSUE TITLE
Crashing with invalid files

### ISSUE THREAD

**Issue by audiocommander** [syedhali/EZAudio#56]
In EZAudio.m, line 231: `+checkResult:operation:`
you are calling exit(1) which crashes the app rather abruptly. It would be a bit nicer to raise an exception instead that we can catch:

    231: //exit(1);
    232: [NSException raise:@"Error: " format:@"%s (%s)\n", operation, errorString];

btw: I'm on Mac OS X, 10.9.3, latest Xcode, latest EZAudio (0.0.5).
EZAudio is really great, thanks for sharing  <3

**Comment by syedhali** [comment]
As of the 0.1.0 release can just globally set `setShouldExitOnCheckResultFail:` to NO on the EZAudioUtilities class to prevent EZAudio from exiting the application.

```objectivec
[EZAudioUtilities setShouldExitOnCheckResultFail:NO];
```
