### ISSUE TITLE
EZAudioFile EXC_BAD_ACCESS when seeking too much...

### ISSUE THREAD

**Issue by cutmaster** [syedhali/EZAudio#60]
Hello, when using to often the seekToFrame method while playing a file, the application crashes on EXC_BAD_ACCESS on line 167 
[EZAudio checkResult:ExtAudioFileRead(_audioFile,
                                          &frames,
                                          audioBufferList)
               operation:"Failed to read audio data from audio file"];

![capture d ecran 2014-06-08 19 00 09](https://cloud.githubusercontent.com/assets/851681/3211765/b2b80db6-ef2e-11e3-81e9-f3f77e7d2c8b.png)

**Comment by syedhali** [comment]
This should be fixed in the 0.3.0 release. Read/seek operations are wrapped in a mutex lock to make sure things are thread-safe.
