### ISSUE TITLE
Xcode 6: 'AudioUnitSampleType' is deprecated and no AudioPlotGL graph

### ISSUE THREAD

**Issue by avelasquezn** [syedhali/EZAudio#67]
I'm using  EZAudio for a sound recording and playing app in iPhone, with Xcode 6 Beta 3 and Swift. 

At this time I've successfully compiled and deployed the app for testing both in the simulator and my device.

Xcode 6 identifies 20 warning issues for EZAudio, in the classes: EZOutput, EZAudioFile and EZAudio with the following messages:
```
"'AudioUnitSampleType' is deprecated: The concept of canonical formats is deprecated"
"'kAudioFormatFlagsCanonical' is deprecated: The concept of canonical formats is deprecated"
"'AudioSessionGetProperty' is deprecated: first deprecated in iOS 7.0"
"Apple Mach-O Linker warning: relocatable dylibs (e.g. embedded frameworks) are only supported on iOS 8.0 and later (@rpath/libswift_stdlib_core.dylib)"

```
When compiled, the app can record a sound and play it. The problem is in the live recording sound graph. I added an EZAudioPilotGL var to the ViewController class:
```
  @IBOutlet var audioPlot: EZAudioPlotGL
```
Its dimensions: w: 320, h: 62. View Mode: Scale to Fill.
 
I also included the following lines in the viewDidLoad method.
```
    self.microphone = EZMicrophone(delegate: self) 
    self.audioPlot.backgroundColor = UIColor.clearColor()
    self.audioPlot.color = UIColor.orangeColor()
    self.audioPlot.plotType = EZPlotType.Rolling
    self.audioPlot.opaque = false
    self.view.opaque = false
    self.audioPlot.shouldFill = true
    self.audioPlot.shouldMirror = true
```
I have ported to Swift all the methods implemented in the example project EZAudioRecordExample, including the microphone methods and the audioPlayerDidFinishPlaying method:
```
  func microphone(microphone: EZMicrophone, hasAudioReceived buffer: CMutablePointer<Float>, withBufferSize bufferSize: UInt32, withNumberOfChannels numberOfChannels: UInt32) {
    dispatch_async(dispatch_get_main_queue(), {
      println("Updating AudioPlot Buffer")
      self.audioPlot.updateBuffer(buffer, withBufferSize: bufferSize)
      println("bufferSize \(bufferSize)")
    })
  }
  
  func microphone(microphone: EZMicrophone, hasBufferList bufferList:CMutablePointer<AudioBufferList>, withBufferSize bufferSize:UInt32, withNumberOfChannels numberOfChannels:UInt32){
    println(microphone)
    println(bufferList)
    if (self.isRecording) {
          self.recorder!.appendDataFromBufferList(bufferList, withBufferSize:bufferSize)
        }
  }
  
  func audioPlayerDidFinishPlaying(player: AVAudioPlayer, successfully flag: Bool) {
    self.isPlaying = false
    togglePlaying()
  }
```
During the recording session, the AudioPilot remains just black, with no graph appearing.

I Also verified the ported methods are being called.

Any help for a solution would be very appreciated.

**Comment by davidwadge** [comment]
I'm having the same issue as @avelasquezn - no audio is plotted. In my scenario I can see that there's nothing coming in via the mic as the Swift gist below will show.

Any ideas what's causing this? I have tried playing around with the AudioSession but no such luck.

Here's a [gist](https://gist.github.com/davidwadge/10986e80adf6612f7bff "Gist") illustrating the problem.

**Comment by syedhali** [comment]
As of 0.0.6 EZAudio doesn't use AudioUnitSampleType values anymore, just floats. Judging by the response on @davidwadge's gist there might've been some Swift bridging weirdness that caused issues, but other people were able to make it work. Going to close this for now.
