### ISSUE TITLE
exit(1) in +(void)checkResult:(OSStatus)result operation:(const char *)operation

### ISSUE THREAD

**Issue by tspecht** [syedhali/EZAudio#82]
I started using EZAudio today and wondered why exit(1) is called at the end?

**Comment by AriX** [comment]
Would be great if you'd make this change - exiting the program is helpful for neither the user nor debugging!

**Comment by shannonchou** [comment]
I'm waiting for this change.

**Comment by AriX** [comment]
@shannonchou, feel free to use my branch here: https://github.com/DeskConnect/EZAudio/commits/master

**Comment by shannonchou** [comment]
Thanks @AriX ! I merged you commit on my fork. Now the main problem is that, I'm using swift in my project. Swift can not catch the exception throwed by Objective-C. I suppose changing the source code is the only way.

**Comment by sabymike** [comment]
@shannonchou Not the best solution but I have the same problem and ended up using this. It gets the job done.

https://github.com/williamFalcon/SwiftTryCatch

**Comment by shannonchou** [comment]
@sabymike Cool！It's useful. I'd love to try it later.

**Comment by syedhali** [comment]
See #56. 

In short - as of the 0.1.0 release can just globally set setShouldExitOnCheckResultFail: to NO on the EZAudioUtilities class to prevent EZAudio from exiting the application.

```objectivec
[EZAudioUtilities setShouldExitOnCheckResultFail:NO];
```

**Comment by AriX** [comment]
Thanks for adding this. I would strongly suggest that NO be the default here. Exiting on error is completely unreasonable behavior for any production software, and most users of EZAudio probably won't be aware of this category.
