### ISSUE TITLE
Changing Buffer Size

### ISSUE THREAD

**Issue by LukasJoswiak** [syedhali/EZAudio#84]
I have been searching for a way to change the buffer size to increase the number of data points received per second.

This issue (https://github.com/syedhali/EZAudio/issues/50) is similar to what I am trying to do, but there does not appear to be an answer. How do I decrease the buffer size?

Thanks!

**Comment by jamrader** [comment]
JeanRintoul or LikasJoswiak, did either of you manage to get a FFTViewController that could measure the Hz of a sound through the microphone with greater accuracy than that which is provided for with a buffer size of 512? I'm trying to manage increasing its accuracy (most likely by increasing buffer size) but am coming up short.

**Comment by syedhali** [comment]
As of 1.1.0 you can just use the EZAudioFFTRolling to get an FFT with a larger window. Please check out the answer for #185 for a code example of how to store more than 512 audio samples using an EZPlotHistoryInfo structure. 

Also, the [EZAudioFFTExample](https://github.com/syedhali/EZAudio/tree/master/EZAudioExamples/iOS/EZAudioFFTExample) has been updated to be a high resolution pitch detector using a 4096 length FFT.
![FFTExample](https://cloud.githubusercontent.com/assets/1275640/8662077/5621705a-2971-11e5-88ed-9a865e422ade.gif)
