### ISSUE TITLE
Switching microphones

### ISSUE THREAD

**Issue by peterpaulis** [syedhali/EZAudio#86]
Support for switching microphone source
https://developer.apple.com/library/IOS/qa/qa1799/_index.html#//apple_ref/doc/uid/DTS40013720

**Comment by syedhali** [comment]
As of 0.1.0 the EZMicrophone now supports setting different EZAudioDevice instances that wrap the AVAudioSession API for iOS and the AudioObject API for OSX.

Specifically, you can first get an array of devices from the EZAudioDevice class via:
```objectivec
//------------------------------------------------------------------------------
// @name Getting The Devices
//------------------------------------------------------------------------------

/**
 Enumerates all the available input devices and returns the result in an NSArray of EZAudioDevice instances.
 @return An NSArray containing EZAudioDevice instances, one for each available input device.
 */
+ (NSArray *)inputDevices;
```

and then just set one of them on the EZMicrophone instance using the following method:
```objectivec
/**
 Sets the EZAudioDevice being used to pull the microphone data.
 - On iOS this can be any of the available microphones on the iPhone/iPad devices (usually there are 3). Defaults to the first microphone found (bottom mic)
 - On OSX this can be any of the plugged in devices that Core Audio can detect (see kAudioUnitSubType_HALOutput for more information)
 System Preferences -> Sound for the available inputs)
 @param device An EZAudioDevice instance that should be used to fetch the microphone data.
 */
- (void)setDevice:(EZAudioDevice *)device;
```

Check out the new EZAudioCoreGraphicsWaveformExample project where you can now select from any of the different microphones.
![img_1871](https://cloud.githubusercontent.com/assets/1275640/8400105/03051862-1dce-11e5-97ef-c91fc568d07c.PNG)
