### ISSUE TITLE
Get audio data without playback

### ISSUE THREAD

**Issue by codegastudio** [syedhali/EZAudio#90]
Before all, thank you very much for your work.
It's easy to use. 
If i just can make a suggestion, perhaps you will separate audio core processing from audio plot system but it's not really important.
It's easy to create your own data viewer when you are available to handle buffer data. So we don't really need to embed audio plot files.

My question :
I need to get sound data from file without play it.
I had test with "seekFrame" and "getWaveformDataWithCompletionBlock" but when i set a frame index value different of 0 i get crash.
Any idea ?
The goal is to create video with sound wave animation.
I need to process waveform updated on each image.
I would like do that without playing sound and lock user during processing.

Thank you in advance for your advise.

**Comment by syedhali** [comment]
The EZAudioFile in the 0.3.0 release should provide you with what you need. Specifically you can read in the audio samples using the `readFrames:audioBufferList:bufferSize:eof:` method. The getWaveformDataWithCompletionBlock has also been fixed (it had a bug before that would cause it to crash if called too many times).

**Comment by kosso** [comment]
@codegastudio Hi. I am trying to do the same thing: Get the waveform data, then use this to generate a video (maybe using AVAssetWriter, AVMutableComposition and CALayers?) - using the recorded audio as the audio track (and 'timer').

I know this is an old thread, but did you ever find come up with a way to do it? (ie: is it possible?)

Many thanks!
